import { ClerkProvider, SignInButton, SignUpButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'RideMate',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedOut>
            <SignInButton className="px-4 py-2 text-white rounded-4xl hover:bg-gray-800 transition-all duration-200" />
            <SignUpButton className="px-4 py-2 bg-gray-400 text-white rounded-4xl hover:bg-gray-800 transition-all duration-200" />
            </SignedOut>
            <SignedIn>
              <UserButton/>
            </SignedIn>
          </div>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
